apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ICOS-metrics-export.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ICOS-metrics-export.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "ICOS-metrics-export.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if (tpl .Values.extraCertsBundle.configmapName .) }}
      volumes:
        - configMap:
            name: {{ tpl .Values.extraCertsBundle.configmapName . }}
          name: extra-certs-bundle
        - emptyDir: {}
          name: tmp
      {{- end }}

      {{- if (tpl .Values.extraCertsBundle.configmapName .) }}
      initContainers:
        - name: init-ca-certs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
          args:
            - |
              cp /etc/ssl/certs/ca-certificates.crt /output/
              cat /extra-certs/intermediate-ca.pem >> /output/ca-certificates.crt
              cat /extra-certs/root-ca.pem >> /output/ca-certificates.crt
              update-ca-certificates
          volumeMounts:
            - mountPath: /extra-certs/intermediate-ca.pem
              name: extra-certs-bundle
              subPath: intermediate-ca.pem
            - mountPath: /extra-certs/root-ca.pem
              name: extra-certs-bundle
              subPath: root-ca.pem
            - mountPath: /output
              name: tmp
              readOnly: false
      {{- end }}

      containers:
        - name: {{ include "ICOS-metrics-export.fullname" . }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-icos-metrics-export-config
          {{- if (tpl .Values.extraCertsBundle.configmapName .) }}
          volumeMounts:
            - mountPath: /etc/ssl/certs/icos-extra-certs.crt
              name: extra-certs-bundle
              subPath: {{ tpl .Values.extraCertsBundle.configmapKey . }}
            - mountPath: /etc/ssl/certs/ca-certificates.crt
              name: tmp
              subPath: ca-certificates.crt
          {{- end }}
