apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ICOS-metrics-export.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ICOS-metrics-export.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "ICOS-metrics-export.fullname" . }}
      annotations:
        # enable/disable the collection of logs from this pod
        # Default: false
        logs.icos.eu/scrape: "true"
    spec:
      {{- with .Values.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
#      nodeSelector:
#        tier: "controller"
      containers:
        - name: {{ include "ICOS-metrics-export.fullname" . }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.port }}"
            - name: INTELLIGENCE_API_MODEL_INFERENCE_BASE_URL
              value: "{{ tpl .Values.INTELLIGENCE_API_MODEL_INFERENCE_BASE_URL . }}"
            - name: INTELLIGENCE_API_MODEL_TRAINING_URL
              value: "{{ tpl .Values.INTELLIGENCE_API_MODEL_TRAINING_URL . }}"
            - name: GRAFANA_API_BASE_URL
              value: "{{ tpl .Values.GRAFANA_API_BASE_URL . }}"
            - name: GRAFANA_SERVICE_ACCOUNT_BEARER_TOKEN
              value: "{{ tpl .Values.GRAFANA_SERVICE_ACCOUNT_BEARER_TOKEN . }}"
            - name: GRAFANA_DATASOURCE_UID
              value: "{{ tpl .Values.GRAFANA_DATASOURCE_UID . }}"
            - name: GRAFANA_INTERVAL_MS
              value: "{{ .Values.GRAFANA_INTERVAL_MS }}"
            - name: INTERVAL_IN_SECONDS_FOR_METRICS_EXPORT
              value: "{{ .Values.INTERVAL_IN_SECONDS_FOR_METRICS_EXPORT }}"
            - name: GRAFANA_UTC_OFFSET_SEC
              value: "{{ .Values.GRAFANA_UTC_OFFSET_SEC }}"
            - name: DATACLAY_HOST
              value: "{{ tpl .Values.DATACLAY_HOST . }}"
            - name: DATACLAY_USERNAME
              value: "{{ tpl .Values.DATACLAY_USERNAME . }}"
            - name: DATACLAY_PASSWORD
              value: "{{ tpl .Values.DATACLAY_PASSWORD . }}"
            - name: PROMETHEUS_METRICS_DISABLED
              value: "{{ tpl .Values.PROMETHEUS_METRICS_DISABLED | quote }}"
            - name: SECURITY_DISABLED
              value: "{{ tpl .Values.SECURITY_DISABLED | quote }}"
            - name: KEYCLOAK_SERVER_URL
              value: "{{ tpl .Values.KEYCLOAK_SERVER_URL . }}"
            - name: KEYCLOAK_REALM_NAME
              value: "{{ tpl .Values.KEYCLOAK_REALM_NAME . }}"
            - name: KEYCLOAK_RESOURCE_SERVER_ID
              value: "{{ tpl .Values.KEYCLOAK_RESOURCE_SERVER_ID . }}"
            - name: KEYCLOAK_AUDIENCE
              value: "{{ tpl .Values.KEYCLOAK_AUDIENCE . }}"
            - name: KEYCLOAK_CLIENT_ID
              value: "{{ tpl .Values.KEYCLOAK_CLIENT_ID . }}"
            - name: KEYCLOAK_CLIENT_SECRET_KEY
              value: "{{ tpl .Values.KEYCLOAK_CLIENT_SECRET_KEY . }}"