apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ICOS-metrics-export.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ICOS-metrics-export.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install