#  ICOS Metrics Export to Prometheus
#  Copyright © 2022-2024 National and Kapodistrian University of Athens
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#  This work has received funding from the European Union's HORIZON research
#  and innovation programme under grant agreement No. 101070177.

# Default values for ICOS-metrics-export.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
name: icos-export-metrics
port: 9600

image:
  name: menelaoszetas/icos_metrics
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: NodePort
  ports:
    - port: 9600
      targetPort: 9600
      nodePort: 30608


INTELLIGENCE_API_MODEL_INFERENCE_BASE_URL: 'http://10.160.3.160:3000/'
INTELLIGENCE_API_MODEL_TRAINING_URL: 'http://10.160.3.160:3000/'

# NKUA URL
#GRAFANA_API_BASE_URL: 'http://91.138.223.127:30009/'
# NCSRD URL
GRAFANA_API_BASE_URL: 'http://10.160.3.20:32100/'

# NKUA Service Account Token
#GRAFANA_SERVICE_ACCOUNT_BEARER_TOKEN: 'glsa_9fdUHcnFEwRYZRFrsTFT6wjsAjj0bYN1_0dd59558'
# NCSRD Service Account Token
GRAFANA_SERVICE_ACCOUNT_BEARER_TOKEN: 'glsa_mmrOBm0J8PYxjKjDk49JdvliP9sabnJp_313a14df'

# NKUA grafana datasource uid
#GRAFANA_DATASOURCE_UID: 'PBFA97CFB590B2093'
# NCSRD grafana datasource uid
GRAFANA_DATASOURCE_UID: 'a151c53f-db08-4d10-a3b8-97ef5f2d614f'

# must be the same and at least equal to prometheus interval
GRAFANA_INTERVAL_MS: 60000
INTERVAL_IN_SECONDS_FOR_METRICS_EXPORT: 60
# UTC of server that grafana is deployed
GRAFANA_UTC_OFFSET_SEC: 7200

DATACLAY_HOST: '127.0.0.1'
DATACLAY_USERNAME: 'testuser'
DATACLAY_PASSWORD: 's3cret'

#imagePullSecrets: []
#nameOverride: ""
#fullnameOverride: ""

#serviceAccount:
  # Specifies whether a service account should be created
#  create: true
  # Automatically mount a ServiceAccount's API credentials?
#  automount: true
  # Annotations to add to the service account
#  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
#  name: ""

podAnnotations: {}
podLabels: {
  app: icos-export-custom-metrics-to-prometheus
}

#podSecurityContext: {}
  # fsGroup: 2000

#securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

#ingress:
#  enabled: false
#  className: ""
#  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
#  hosts:
#    - host: chart-example.local
#      paths:
#        - path: /
#          pathType: ImplementationSpecific
#  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

#resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

#livenessProbe:
#  httpGet:
#    path: /
#    port: http
#readinessProbe:
#  httpGet:
#    path: /
#    port: http

#autoscaling:
#  enabled: false
#  minReplicas: 1
#  maxReplicas: 100
#  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
#volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
#volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

#nodeSelector: {}

#tolerations: []

#affinity: {}
