import os
import logging

# set a logger
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

INTERVAL_IN_SECONDS_FOR_METRICS_EXPORT = int(os.getenv('INTERVAL_IN_SECONDS_FOR_METRICS_EXPORT', 60))

INTELLIGENCE_API_MODEL_INFERENCE_BASE_URL = os.getenv('INTELLIGENCE_API_MODEL_INFERENCE_BASE_URL', 'http://10.160.3.160:3000/predict_model')
INTELLIGENCE_API_MODEL_TRAINING_URL = os.getenv('INTELLIGENCE_API_MODEL_TRAINING_URL', 'http://10.160.3.160:3000/train_model')

# NKUA
# GRAFANA_API_BASE_URL = os.getenv('GRAFANA_API_BASE_URL', 'http://91.138.223.127:30009/')
# NCSRD
GRAFANA_API_BASE_URL = os.getenv('GRAFANA_API_BASE_URL', 'http://10.160.3.20:32100/')

#NCSRD
GRAFANA_SERVICE_ACCOUNT_BEARER_TOKEN = os.getenv('GRAFANA_SERVICE_ACCOUNT_BEARER_TOKEN', ' ')

# REMOVE IF NO LONGER NEEDED
# NKUA
# GRAFANA_SERVICE_ACCOUNT_BEARER_TOKEN = os.getenv('GRAFANA_SERVICE_ACCOUNT_BEARER_TOKEN', 'glsa_9fdUHcnFEwRYZRFrsTFT6wjsAjj0bYN1_0dd59558')
# NCSRD
# GRAFANA_SERVICE_ACCOUNT_BEARER_TOKEN = os.getenv('GRAFANA_SERVICE_ACCOUNT_BEARER_TOKEN', 'glsa_mmrOBm0J8PYxjKjDk49JdvliP9sabnJp_313a14df')

GRAFANA_INTERVAL_MS = int(os.getenv('GRAFANA_INTERVAL_MS', 60000))
GRAFANA_UTC_OFFSET_SEC = int(os.getenv('GRAFANA_UTC_OFFSET', 7200))

# NKUA
# GRAFANA_DATASOURCE_UID = os.getenv('GRAFANA_DATASOURCE_UID', 'PBFA97CFB590B2093')
# NCSRD
GRAFANA_DATASOURCE_UID = os.getenv('GRAFANA_DATASOURCE_UID', 'a151c53f-db08-4d10-a3b8-97ef5f2d614f')

DATACLAY_HOST = os.getenv('DATACLAY_HOST', '127.0.0.1')
DATACLAY_USERNAME = os.getenv('DATACLAY_USERNAME', 'testuser')
DATACLAY_PASSWORD = os.getenv('DATACLAY_PASSWORD', 's3cret')

PROMETHEUS_METRICS_DISABLED = os.getenv('PROMETHEUS_METRICS_DISABLED', False)
SECURITY_DISABLED = os.getenv('SECURITY_DISABLED', True)

KEYCLOAK_SERVER_URL = os.getenv('KEYCLOAK_SERVER_URL', 'http://keycloak:8080')
KEYCLOAK_REALM_NAME = os.getenv('KEYCLOAK_REALM_NAME', 'icos')
KEYCLOAK_RESOURCE_SERVER_ID = os.getenv('KEYCLOAK_RESOURCE_SERVER_ID', 'Default Resource')
KEYCLOAK_AUDIENCE = os.getenv('KEYCLOAK_AUDIENCE', 'Default Resource')
KEYCLOAK_CLIENT_ID = os.getenv('KEYCLOAK_CLIENT_ID', 'coordination')
KEYCLOAK_CLIENT_SECRET_KEY = os.getenv('KEYCLOAK_CLIENT_SECRET_KEY', 'Km4OI7UNO1i4iOwQfUBAJ6rW4INSEyFD')
