import os

# PROMETHEUS_BASE_URL = os.getenv('PROMETHEUS_BASE_URL', 'http://91.138.223.127:30008/api/v1/query_range')
PROMETHEUS_BASE_URL = os.getenv('PROMETHEUS_BASE_URL', 'http://10.160.3.20:32104/api/v1/query_range')
INTERVAL_IN_SECONDS_FOR_METRICS_EXPORT = int(os.getenv('INTERVAL_IN_SECONDS_FOR_METRICS_EXPORT', 60))

INTELLIGENCE_API_MODEL_INFERENCE_BASE_URL = os.getenv('INTELLIGENCE_API_MODEL_INFERENCE_BASE_URL',
                                                      'http://10.160.3.151:3000/')
INTELLIGENCE_API_MODEL_TRAINING_URL = os.getenv('INTELLIGENCE_API_MODEL_TRAINING_URL', 'http://10.160.3.151:3000/')

GRAFANA_API_BASE_URL = os.getenv('GRAFANA_API_BASE_URL', 'http://91.138.223.127:30009/')
GRAFANA_SERVICE_ACCOUNT_BEARER_TOKEN = os.getenv('GRAFANA_SERVICE_ACCOUNT_BEARER_TOKEN',
                                                 'glsa_9fdUHcnFEwRYZRFrsTFT6wjsAjj0bYN1_0dd59558')
GRAFANA_INTERVAL_MS = int(os.getenv('GRAFANA_INTERVAL_MS', 10000))
GRAFANA_UTC_OFFSET_SEC = int(os.getenv('GRAFANA_UTC_OFFSET', 7200))

DATACLAY_HOST = os.getenv('DATACLAY_HOST', '127.0.0.1')
DATACLAY_USERNAME = os.getenv('DATACLAY_USERNAME', 'testuser')
DATACLAY_PASSWORD = os.getenv('DATACLAY_PASSWORD', 's3cret')
